name: CI for mba

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python, java]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Set up JDK 17
      if: matrix.language == 'java'
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies for Python
      if: matrix.language == 'python'
      run: |
        cd mba
        pip install -r requirements.txt

    - name: Build and test Java project
      if: matrix.language == 'java'
      run: |
        cd mba
        ./gradlew build
        ./gradlew test

    - name: Run tests for Python
      if: matrix.language == 'python'
      run: |
        cd mba
        pytest
