name: CI for origamid

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'origamid/**'  # Executa o CI apenas quando arquivos em 'origamid/' forem modificados
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'origamid/**'  # Executa o CI apenas para PRs que modificam arquivos em 'origamid/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build static assets
      run: echo "No build step required for static assets"
