name: CI for plataformaFilmes

on:
  push:
    paths:
      - 'plataformaFilmes/**'
  pull_request:
    paths:
      - 'plataformaFilmes/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Build with Gradle
      run: |
        cd plataformaFilmes
        ./gradlew build
        
    - name: Run tests
      run: |
        cd plataformaFilmes
        ./gradlew test
